services:
  - type: web
    name: chatly-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false 