services:
  - type: web
    name: chatly-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: chatly_jwt_secret_key_for_production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://chatly-frontend.onrender.com
      - key: OPENAI_API_KEY
        sync: false 